const fish = [
    //If I give people the option to filter by weather and season, have to account for 'Any' values
    //Location will have to be an array to account for different types and areas
{
    name: "Albacore",
    type: "Fishing-Pole",
    description: "Prefers temperature 'edges' where cool and warm water meet.",
    location: ["Ocean"],
    time: "6am-11am & 6pm-2am",
    season: ["Fall", "Winter"],
    weather: "Any",
    size: "20in-41in",
    difficulty: "60",
    behavior: "Mixed",
    imgSrc: "https://stardewvalleywiki.com/mediawiki/images/e/e1/Albacore.png"
},
{
    name: "Anchovy",
    type: "Fishing-Pole",
    description: "A small silver fish found in the ocean.",
    location: ["Ocean"],
    time: "Any",
    season: ["Spring", "Fall"],
    weather: "Any",
    size: "1in-17in",
    difficulty: "30",
    behavior: "Dart",
    imgSrc: "https://stardewvalleywiki.com/mediawiki/images/7/79/Anchovy.png"
},
{
    name: "Blue-Discus",
    type: "Fishing-Pole",
    description: "A brightly colored tropical fish that is popular in aquariums.",
    location: [""],
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: "https://stardewvalleywiki.com/mediawiki/images/e/ee/Blue_Discus.png"
},
{
    name: "Bream",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Bullhead",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Carp",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Catfish",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Chub",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Dorado",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Eel",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Flounder",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Ghostfish",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Halibut",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Herring",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Ice-Pip",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Largemouth-Bass",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Lava-Eel",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Lingcod",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Lionfish",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Midnight-Carp",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Octopus",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Perch",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Pike",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Pufferfish",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Rainbow-Trout",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Red-Snapper",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Salmon",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Sandfish",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Sardine",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Scorpion-Carp",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Sea-Cucumber",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Shad",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Slimejack",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Smallmouth-Bass",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Squid",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Stingray",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Stonefish",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Sturgeon",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Sunfish",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Super-Cucumber",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Tiger-Trout",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Tilapia",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Tuna",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Void-Salmon",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Walleye",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Woodskip",
    type: "Fishing-Pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Midnight-Squid",
    type: "night-market",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Spook-Fish",
    type: "night-market",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Blobfish",
    type: "night-market",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Crimsonfish",
    type: "legendary",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Angler",
    type: "legendary",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Legend",
    type: "legendary",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Glacierfish",
    type: "legendary",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Mutant-Carp",
    type: "legendary",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Son-of-Crimsonfish",
    type: "legendary-II",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Ms.-Angler",
    type: "legendary-II",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Legend-II",
    type: "legendary-II",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Glacierfish-Jr.",
    type: "legendary-II",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Radioactive-Carp",
    type: "legendary-II",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Lobster",
    type: "crab-pot",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Clam",
    type: "crab-pot",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Crayfish",
    type: "crab-pot",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Crab",
    type: "crab-pot",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Cockle",
    type: "crab-pot",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Mussel",
    type: "crab-pot",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Shrimp",
    type: "crab-pot",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Snail",
    type: "crab-pot",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Periwinkle",
    type: "crab-pot",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Oyster",
    type: "crab-pot",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
];

module.exports = fish;