const fish = [
{
    name: "Albacore",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Anchovy",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Blue-Discus",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Bream",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Bullhead",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Carp",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Catfish",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Chub",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Dorado",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Eel",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Flounder",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Ghostfish",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Halibut",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Herring",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Ice-Pip",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Largemouth-Bass",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Lava-Eel",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Lingcod",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Lionfish",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Midnight-Carp",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Octopus",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Perch",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Pike",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Pufferfish",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Rainbow-Trout",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Red-Snapper",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Salmon",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Sandfish",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Sardine",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Scorpion-Carp",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Sea-Cucumber",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Shad",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Slimejack",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Smallmouth-Bass",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Squid",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Stingray",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Stonefish",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Sturgeon",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Sunfish",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Super-Cucumber",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Tiger-Trout",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Tilapia",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Tuna",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Void-Salmon",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Walleye",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Woodskip",
    type: "fishing-pole",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Midnight-Squid",
    type: "night-market",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Spook-Fish",
    type: "night-market",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
{
    name: "Blobfish",
    type: "night-market",
    description: "",
    location: "",
    time: "",
    season: "",
    weather: "",
    size: "",
    difficulty: "",
    behavior: "",
    imgSrc: ""
},
];

module.exports = fish;