const weapons = [
//types: sword, dagger, club, slingshot (slingshot ammo?), unobtainable
{
    name: "Rusty Sword",
    type: "Sword",
    level: 1,
    description: "A rusty, dull old sword.",
    damage: "2-5",
    criticalStikeChance: .02,
    stats: "N/A",
    found: "The Mines entrance",
    purchasePrice: "N/A",
    sellPrice: "50g",
    imgSrc: "https://stardewvalleywiki.com/mediawiki/images/d/d7/Rusty_Sword.png"
},
{
    name: "Steel Smallsword",
    type: "Sword",
    level: 1,
    description: "A standard metal blade.",
    damage: "4-8",
    criticalStikeChance: ".02",
    stats: "Speed (+2)",
    found: "The Mines floor 20 chest reward",
    purchasePrice: "N/A",
    sellPrice: "50g",
    imgSrc: "https://stardewvalleywiki.com/mediawiki/images/d/da/Steel_Smallsword.png"
},
{
    name: "Wooden Blade",
    type: "Sword",
    level: 1,
    description: "Not bad for a piece of carved wood.",
    damage: "3-7",
    criticalStikeChance: ".02",
    stats: "N/A",
    found: "The Mines floor 10 chest reward (remixed mine rewards only), Adventurer's Guild",
    purchasePrice: "250g",
    sellPrice: "50g",
    imgSrc: "https://stardewvalleywiki.com/mediawiki/images/0/06/Wooden_Blade.png"
},
{
    name: "Pirate's Sword",
    type: "Sword",
    level: 2,
    description: "",
    damage: "",
    criticalStikeChance: "",
    stats: "",
    found: "",
    purchasePrice: "",
    sellPrice: "",
    imgSrc: ""
},
{
    name: "",
    type: "Sword",
    level: ,
    description: "",
    damage: "",
    criticalStikeChance: "",
    stats: "",
    found: "",
    purchasePrice: "",
    sellPrice: "",
    imgSrc: ""
},
{
    name: "",
    type: "Sword",
    level: ,
    description: "",
    damage: "",
    criticalStikeChance: "",
    stats: "",
    found: "",
    purchasePrice: "",
    sellPrice: "",
    imgSrc: ""
},
{
    name: "",
    type: "Sword",
    level: ,
    description: "",
    damage: "",
    criticalStikeChance: "",
    stats: "",
    found: "",
    purchasePrice: "",
    sellPrice: "",
    imgSrc: ""
},
{
    name: "",
    type: "Sword",
    level: ,
    description: "",
    damage: "",
    criticalStikeChance: "",
    stats: "",
    found: "",
    purchasePrice: "",
    sellPrice: "",
    imgSrc: ""
},
{
    name: "",
    type: "Sword",
    level: ,
    description: "",
    damage: "",
    criticalStikeChance: "",
    stats: "",
    found: "",
    purchasePrice: "",
    sellPrice: "",
    imgSrc: ""
},
{
    name: "",
    type: "Sword",
    level: ,
    description: "",
    damage: "",
    criticalStikeChance: "",
    stats: "",
    found: "",
    purchasePrice: "",
    sellPrice: "",
    imgSrc: ""
},
{
    name: "",
    type: "Sword",
    level: ,
    description: "",
    damage: "",
    criticalStikeChance: "",
    stats: "",
    found: "",
    purchasePrice: "",
    sellPrice: "",
    imgSrc: ""
},
{
    name: "",
    type: "Sword",
    level: ,
    description: "",
    damage: "",
    criticalStikeChance: "",
    stats: "",
    found: "",
    purchasePrice: "",
    sellPrice: "",
    imgSrc: ""
},
{
    name: "",
    type: "Sword",
    level: ,
    description: "",
    damage: "",
    criticalStikeChance: "",
    stats: "",
    found: "",
    purchasePrice: "",
    sellPrice: "",
    imgSrc: ""
},
{
    name: "",
    type: "Sword",
    level: ,
    description: "",
    damage: "",
    criticalStikeChance: "",
    stats: "",
    found: "",
    purchasePrice: "",
    sellPrice: "",
    imgSrc: ""
},
];

module.exports = weapons;